const String kAppFolder = 'InspectW';
const Map<String, List<String>> kInstitucionesEducativasGroups = {
  'A. EXTINTORES': [
    '1.3.2	Está en un lugar accesible?',
    '1.3.2	Está colgado o en pedestal?',
    '1.3.2	Altura menor a 1.50m?',
    '1.3.2	Está señalizado foto. según tipo?',
    '1.3.2	N° en la señalet.?',
    '1.3.2	N° en el extintor?',
    '1.3.2	Tiene tarjeta de control?',
    '1.3.2	Está correctamente llenada?',
    '1.3.2	Tiene precinto de seguridad?',
    '1.3.3	Interperie - en gabinete?',
    '1.3.3	Estado del gabinete',
  ],
  'B. TABLEROS': [
    '1.1.3	Cuenta con señalizacion de RIESGO ELECTRICO fotoluminiscente?',
    '1.2.1	El gabinete del tablero se encuentra en buen estado de conservación?',
    '1.2.2	Cuenta con ITM que corresponden a la capacidad de corriente de los conductores eléctricos que protege?',
    '1.2.3	Cuenta con un circuito eléctrico por cada interruptor termomagnético?',
    '1.2.3	El tablero tiene un interruptor general en su interior o adyacente al mismo?',
    '1.2.6	Los ITM, DIF u otros accesorios cuenta con terminales?',
    '1.2.6	Está libre de empalmes no técnicos dentro del tablero?',
    '1.2.6	Las fases de los circuitos están diferenciados por colores o rotulados?',
    '1.2.6	Los cables son del tipo no propagador del incendio, libre de halógenos?',
    '3.1.1	El tablero eléctrico de material metálico está conectado a tierra?',
    '3.1.1	Todos los circuitos tienen alimentadores de tierra?',
    '3.1.2	El tablero cuenta con placa de protección (mandil)?',
    '3.1.3	Las aberturas no usadas (reserva) se encuentran cerradas con tapas?',
    '3.1.4	Todos los circuitos eléctricos tienen protección de interruptores diferenciales?',
    '3.1.17	Los diagramas unifilares concuerdan con lo verificado físicamente?',
    '3.3.7	El(los) tablero(s) eléctrico(s) cuenta(n) con identificación?',
    '3.3.8	Tiene directorio de los circuitos, indicando de manera visible y clara la instalación que controla?',
    '3.3.8	Los circuitos se encuentran debidamente rotulados?',
    '3.3.9	Existe espacio libre no menor a un metro frente a los tableros eléctricos?',
    '3.3.10	Existe iluminación general y de emergencia en la zona de ubicación de los tableros eléctricos?',
    'S/N	Otras observaciones',
  ],
  'C. AMBIENTES': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.9.1	Almacenes, no almacenan productos peligrosos?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los equipos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso y tomacorrientes tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
  'D. PASILLOS': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (120cm)?',
    '1.1.2	Se encuentran libres de obstáculos?',
    '1.1.4	Cuenta con luces de emergencia?',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso y tomacorrientes tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
  'E. PATIOS': [
    '1.1.3	Las salidas estan señalizadas? Hay señal de aforo en los ingresos? La señaletica está en buen estado?',
    '1.1.4	Las salidas cuentan con luces de emergencia?',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '1.1.6	En caso de contener mas de 100 de aforo, las puertas poseen barra antipanico?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.4.1	Hays estaciones manuales cerca a los ingresos?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '2.5.1	Las estructuras de madera presentan apolillamiento o pandeos?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.7	Las carcazas de motoreres electricos, aires acondiconados, bebederos, estan conectados al circuito a tierra?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.1.12	Los tomacorrientes son hermeticos tipo hidrobo o similar?',
    '3.2.1	las rampas tienen pendiente menor de 12%, estan señalizadas con franjas amarillas antideslizantes y tienen barandas a ambos lados?',
    '3.2.3	Las mallas raschel de las coberturas se encuentran en estado optimo, con ojales y armellas sin oxido?',
    '3.3.1	Las estructuras de paneles publicitarios son seguras, tienen anclajes, no presentan óxido o corrosión, inclinaciones?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.3	Las estructuras de soporte de equipos de aire acondicionado, condensadores y otros, están adecuadamente fijadas, no presentan óxido ni corrosión?',
    '3.3.5	Los juegos infantiles de carpintería metálica, de madera o plástico, son estables, seguros, están bien instalados y en buen estado?',
    'S/N	Otras observaciones',
  ],
  'F. ESCALERAS': [
    '1.1.4	Tiene luces de emergencia en su recorrido?',
    '1.1.7	No cuenta con material combustible o inflamable debajo de las escaleras que sirvan como medios de evacuación (cartones, muebles, plásticos otros similares)?',
    '1.1.8	Minimo de ancho de escalera: - 1.20m.(general)- 0.90m.(oficinas, industria o servicios)',
    '1.1.8	Minimo de ancho de paso: -0.25m.(industria), -0.28m.(comercio, oficinas, hospedaje, servcios comunales)., -0.30m. (educación, salud, recreacion, deportes, transporte).',
    '1.1.8	Minimo de alto de contrapaso: 0.18m. (general).',
    '1.1.8	Minimo ancho de descanso:- 0.90m. (escalera lineal).- el mismo ancho de la escalera (escalera que dobla)',
    '1.1.8	Tiene pasamanos a ambos lados incluyendo los descansos?',
    '1.1.8	Todos los pasos tienen franjas amarillas?',
    '1.1.8	Todos los filos son antideslizantes?',
    '1.1.9	Las escaleras son continuas desde el primer piso hasta el ultimo piso. (a excepcion del sotano)',
    '1.1.9	Si la escalera sigue al sotano tiene barreras de contencion?',
    '1.3.13	Las escaleras protegidas tienen cerramiento cortafuego?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.2.2	Las escaleras que dan hacia el vacio tienen barandas a 1.00 minimo de altura?',
    '3.2.2	Las barandas al vacio tienen separacion maxima de 15cm (no debe pasar una esfera de 15cm.',
    'S/N	Otras observaciones',
  ],
  'G. CTO. TECNICO': [
    '1.1.3	Posee en el ingreso la señaletica fotoluminiscente de RIESGO ELECTRICO, NO INGRESAR Y USO EPP?',
    '1.1.4	Tiene luces de emergencia operativa e ininterrumpida?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.2	Posee extintor cerca para fuego tipo C?',
    '1.4.1	Tiene detector de humo operativo?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.7	Las carcazas de los equipos electricos, como  racks de servidores, UPS, transformadores, estabilizadores, aires acondiconados, bombas, estan conectados al circuito a tierra? (no considerar a los tableros electricos)',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.3.3	Las estructuras de soporte de equipos de aire acondicionado, racks de servidores o tableros, están adecuadamente fijadas, y no presentan óxido ni corrosión?',
    'S/N	Otras observaciones: Sobre los equipos hay equipos de A.A. o tuberias de agua o desague?',
  ],
  'H. ADMINISTRACION': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.2	Posee extintor cerca para fuego tipo A, B y C?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los equipos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.7	Las carcazas de los equipos electricos, como  racks de servidores, estabilizadores, aires acondiconados, estan conectados al circuito a tierra?',
    '3.1.8	Las mesas o estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.3	Las estructuras de soporte de equipos de racks de servidores y aire acondicionado, están adecuadamente fijadas, y no presentan óxido ni corrosión?',
    '3.3.6	Las mamparas tienen elementos visuales para evitar choques? Hay espejos o vidrios con la lamina de seguridad o son templados?',
    'S/N	Otras observaciones',
  ],
  'I. COCINA': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.1.3	La Valvula de gas posee señaletica?',
    '1.1.4	Tiene luces de emergencia operativa e ininterrumpida?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.5	Las mangueras del tipo flexible de los balones se encuentran en buen estado, sin rajaduras, libres de grasa, limpias, con sujeción firme con abrazaderas',
    '1.3.6	Las tuberias de GLP, son de cobre o fierro galvanizado y estan pintadas? La valvula de gas es accesible?',
    '1.4.1	Tiene detector de humo operativo? O sensor si es que hay plancha de cocina.',
    '1.4.2	Posee extintor cerca y correctamente ubicado para fuego tipo K?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los artefactos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.7	Las campana, esta conectada al circuito a tierra?',
    '3.1.8	Las mesas o estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.1.12	Los tomacorrientes cerca al agua son hidrobox?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.4	La campana de extracción abarca toda la cocina y está en buenas condiciones?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
};

/// Copia de la lista de Instituciones Educativas para ser modificada.
const Map<String, List<String>> kAnexo7aGroups = {
  'A. GENERAL': [
    '1.1.1	Los medios de evacuación (pasadizos, escaleras, accesos y salidas) del establecimiento presentan un ancho mínimo de 1.20 m y/o que permitan la evacuación de las personas de manera segura.',
    '1.1.3	El establecimiento cuenta con señalización de seguridad (direccionales de salida, salida, zona segura en caso de sismo, riesgo eléctrico, extintores, otros).',
    '1.2.4	No utiliza conductores flexibles (tipo mellizo) en instalaciones permanentes de alumbrado y/o tomacorriente.',
    '1.2.7	La alimentación eléctrica a la bomba de agua contra incendios es independiente, no controlada por el interruptor general del edificio e interconectada al grupo electrógeno de emergencia del edificio, en caso de tenerlo.',
    'S/N	Cuenta con botiquin?',
    'S/N	Otras observaciones',
  ],
  'B. MEDIOS PROTECCION CONTRA INCENDIOS': [
    '1.3.4	Cuenta con plan de seguridad para hacer frente a los riesgos de incendio y otros vinculados a la actividad, para establecimientos de dos a más pisos.',
    '1.3.5	Las mangueras del tipo flexible de los cilindros (balones) de Gas Licuado de Petróleo (GLP) tipo 10 (de capacidad hasta 25kg) se encuentran en buen estado de conservación (sin rajaduras, libres de grasa, limpias, con sujeción firme con abrazaderas.',
    '1.3.6	Las instalaciones de GLP que utilizan cilindros tipo 45 (de capacidad mayor a 25Kg), tienen tuberías de cobre o fierro galvanizado.',
    '1.3.7	Los cilindros de GLP están alejados de interruptores a una distancia mayor a 0.30m, y mayor a 0.50m de tomacorrientes, se ubican en lugares ventilados y alejados de cualquier fuente de calor.',
    '1.3.8	Los cilindros de GLP no se encuentran ubicados en nivel de semisótano, sótanos, cajas de escalera, pasillos, pasadizos de uso común y vía pública.',
    '1.3.9	En escaleras presurizadas, la alimentación de energía para los motores del ventilador  debe contar con dos fuentes independientes, de transferencia automática.',
    '1.3.10	El sistema de presurización se encuentra en buen estado de conservación y operativo.',
    '1.3.11	Cuenta con un sistema de proteccion contraincendios a base de agua en función al tipo de edificación, área, altura, y clasificacion del riesgo.',
    '1.3.12	Para todas las edificaciones se debe cumplir con las distancias máximas de recorrido hasta una zona segura exterior o hasta una escalera del tipo de evacuación. Los rociadores son de uso obligatorio en las edificaciones donde sea requerido de acuerdo a la norma en particular de cada tipo de edificación.',
    '1.4.1	Cuenta con un sistema de detección y alarma de incendios centralizado operativo. Se encuentran exceptuados.',
    '1.4.2	Cuenta con extintores operativos en cantidad adecuada de acetato de potasio para ambientes que cuentan con freidora, producen humos y vapores de grasa.',
    '1.9.1	En salas de calderas, la puerta se ubica a una distancia no mayor de 15 metros y abre hacia afuera.Cerramiento en colindancia con ambiente donde se fabriquen, empleen o manipulen material explosivo o altamente inflamable o en colindancia con ambientes de uso publico o vias de evacuacion, se encuetran cerrados completamente con muros resistentes al fuego de minimo 2 horas.',
    '1.9.2	Los elementos de cierre o acabados no presentan caracteristicas de riesgo inflamable o toxico, como poliuretano expandido, espuma plastica, plasticos, cauchos cartones, y similar.',
    '3.3.11	Si el establecimiento cuenta con tanque estacionario de  Gas Licuado de Petróleo (GLP) en cantidades superiores a 0.45m3 (118.18gl) y/o liquido combustible y sus derivados en cantidades a partir de 1m3 (264.17gl), llamado Consumidor Directo, debe tener constancia de registro de hidrocarburos emitido por OSINERGMIN.',
    '3.3.12	En caso de tener caldero: Mostrar el libro del servicio del caldero visado por el Ministerio de Trabajo, el mismo que debe estar actualizado a  la fecha.El nivel del agua del caldero debe encontrarse dentro del rango de mínimo y máximo. La presión de trabajo debe ser menor a la presión indicada por el fabricante. El caldero debe contar con valvula de seguridad, presostato y manómetro.Para el caso del caldero que se encuentre en una ruta de evacuación debe estar cercado con muros de resistencia al fuego. De utilizar combustible GLP o GN no se permite su instalación en sótano.',
    '3.3.13	El caldero se encuentra en buen estado de conservación y mantenimiento.',
    '3.3.14	El caldero se encuentra operado por un personal calificado que cuenta con constancia de capacitación actualizada emitido por profesional o empresa especializada.',
    '3.3.15	Para edificaciones con giro de explosivos, artefactos pirotécnicos y otros afines: Cuenta con sistemas a prueba de explosión, si corresponde.',
    'S/N	Otras observaciones',
  ],
  'C. RIESGO DE COLAPSO': [
    '2.1.1	La cimentación o parte de ella no se encuentra expuesta, inestable en peligro de colapso como consecuencia de filtraciones de agua, erosión, socavamiento, otros.',
    '2.2.1	Las estructuras de concreto no presentan i) fisuras, grietas, rajaduras, deflexiones, pandeos, muros inclinados, varillas de acero expuestas a la intemperie sin recubrimiento en: columnas, vigas, losas de techos, etc., ii) deterioro por humedad producido por: filtraciones, de tanques y cisternas de almacenamiento de agua, de líquidos, tuberías rotas, lluvias, etc., otras fallas estructurales.',
    '2.2.2	Las estructuras de la edificación (losas y vigas de techos, azoteas o losas en niveles intermedios), no presentan fisuras, grietas, rajaduras, pandeos, deflexiones, humedad, otros; como consecuencia de sobrecargas existentes producidas por: tanque elevado, equipos, antenas, panel publicitario, otros.',
    '2.2.3	Los muros de contención en sótanos, en cercos y otros, no presentan fisuras, grietas, rajaduras, deflexiones, pandeos, inclinaciones, varillas de acero expuestas a la intemperie sin recubrimiento, deterioro por humedad producido por filtraciones de tanques y cisternas de almacenamiento de agua, de líquidos, tuberías rotas, lluvias, etc. y otros.',
    '2.3.1	La edificación de albañilería cuenta con elementos de concreto armado de confinamiento, amarre y/o arriostramiento tales como: cimientos, columnas, vigas, losas.',
    '2.3.2	Los muros de albañilería no presentan daños: humedad, rajaduras, grietas, inclinaciones, otros.',
    '2.4.1	Los muros de adobe no presentan fallas ni daños ocasionados por el deterioro y/o humedad (fisuras, grietas, inclinaciones). No es utilizado como muro de contención de suelos, materiales u otros que hagan que pierda su estabilidad. Sobre los muros de adobe no existen construcciones de albañilería o concreto. Los muros de adobe están protegidos de la lluvia en zonas lluviosas.',
    '2.5.1	Las estructuras de madera, bambú, no presentan rajaduras, deflexiones, pandeos, deterioro por apolillamiento, humedad, otros.',
    '2.5.2	Las estructuras (postes, columnas, vigas, viguetas, techos entablados, tijerales o cerchas, etc.), no presentan rajaduras, pandeos, deflexiones, como consecuencia de sobrecargas existentes producidas por: tanque elevado, equipos, antenas, panel publicitario, o como consecuencia de otros usos que impliquen cargas mayores a la que puede soportar la estructura.',
    '2.5.3	La estructura de madera se encuentra alejada o aislada de fuentes de calor que podrían dañarla, o en caso de encontrarse próxima a fuentes de calor, se encuentra protegida con material incombustible y/o tratada con sustancias retardantes o ignifugas.',
    '2.6.1	Las edificaciones o techos de estructura de acero no presentan deformaciones o pandeos excesivos y visibles que perjudiquen su estabilidad. Los apoyos, uniones y anclajes son seguros (tienen pernos y soldaduras en buen estado de conservación).',
    '2.6.2	No presentan deterioro por oxido y/o corrosión y se encuentra protegida contra este.',
    'S/N	Otras observaciones',
  ],
  'D. OTROS RIESGOS': [
    '3.1.9	La carcaza y motor del ascensor, montacargas, escaleras mecánicas y de equipos de elevación eléctrica, deben estar conectados al sistema de puesta a tierra.',
    '3.1.10	El ascensor, montacargas, escaleras mecanicas y equipos de elevacion electrica, cuentan con constancia de operatividad y mantenimiento, firmado por ing. mecánico, electricista o mecánico electricista colegiado y habilitado.',
    '3.1.13	La subestación esta protegida con cercos, tabiques o paredes para limitar el acceso de personas no autorizadas. La estructura metálica esta conectada al sistema de puesta a tierra.',
    '3.1.15	Las máquinas tragamonedas no presentan superficies energizadas y están conectadas al sistema de puesta a tierra.',
    '3.1.16	Los equipos electromecánicos de gimnasios deben estar conectados al sistema de puesta a tierra.',
    '3.2.1	Las rampas tienen una pendiente no mayor al 12% permitiendo la evacuación, tienen pisos antideslizantes y tienen barandas.',
    '3.2.2	Las aberturas al exterior ubicadas a una altura mayor a 1.00 m sobre el suelo, en tragaluces, escaleras y azotea cuentan con protección al vacío de altura mínima de 1.00m, para evitar  caídas al vacío.',
    'S/N	Otras observaciones',
  ],
};

/// Mapa principal que contiene todos los conjuntos de grupos de descripción.
const Map<String, Map<String, List<String>>> kAllDescriptionGroupSets = {
  'Instituciones educativas': kInstitucionesEducativasGroups,
  'Anexo7a': kAnexo7aGroups,
};
