const String kAppFolder = 'InspectW';
const Map<String, List<String>> kDescriptionGroups = {
  'A. EXTINTORES': [
    '1.3.2	Está en un lugar accesible?',
    '1.3.2	Está colgado o en pedestal?',
    '1.3.2	Altura menor a 1.50m?',
    '1.3.2	Está señalizado foto. según tipo?',
    '1.3.2	N° en la señalet.?',
    '1.3.2	N° en el extintor?',
    '1.3.2	Tiene tarjeta de control?',
    '1.3.2	Está correctamente llenada?',
    '1.3.2	Tiene precinto de seguridad?',
    '1.3.3	Interperie - en gabinete?',
    '1.3.3	Estado del gabinete',
  ],
  'B. TABLEROS': [
    '1.1.3	Cuenta con señalizacion de RIESGO ELECTRICO fotoluminiscente?',
    '1.2.1	El gabinete del tablero se encuentra en buen estado de conservación?',
    '1.2.2	Cuenta con ITM que corresponden a la capacidad de corriente de los conductores eléctricos que protege?',
    '1.2.3	Cuenta con un circuito eléctrico por cada interruptor termomagnético?',
    '1.2.3	El tablero tiene un interruptor general en su interior o adyacente al mismo?',
    '1.2.6	Los ITM, DIF u otros accesorios cuenta con terminales?',
    '1.2.6	Está libre de empalmes no técnicos dentro del tablero?',
    '1.2.6	Las fases de los circuitos están diferenciados por colores o rotulados?',
    '1.2.6	Los cables son del tipo no propagador del incendio, libre de halógenos?',
    '3.1.1	El tablero eléctrico de material metálico está conectado a tierra?',
    '3.1.1	Todos los circuitos tienen alimentadores de tierra?',
    '3.1.2	El tablero cuenta con placa de protección (mandil)?',
    '3.1.3	Las aberturas no usadas (reserva) se encuentran cerradas con tapas?',
    '3.1.4	Todos los circuitos eléctricos tienen protección de interruptores diferenciales?',
    '3.1.17	Los diagramas unifilares concuerdan con lo verificado físicamente?',
    '3.3.7	El(los) tablero(s) eléctrico(s) cuenta(n) con identificación?',
    '3.3.8	Tiene directorio de los circuitos, indicando de manera visible y clara la instalación que controla?',
    '3.3.8	Los circuitos se encuentran debidamente rotulados?',
    '3.3.9	Existe espacio libre no menor a un metro frente a los tableros eléctricos?',
    '3.3.10	Existe iluminación general y de emergencia en la zona de ubicación de los tableros eléctricos?',
    'S/N	Otras observaciones',
  ],
  'C. AMBIENTES': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.9.1	Almacenes, no almacenan productos peligrosos?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los equipos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso y tomacorrientes tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
  'D. PASILLOS': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (120cm)?',
    '1.1.2	Se encuentran libres de obstáculos?',
    '1.1.4	Cuenta con luces de emergencia?',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso y tomacorrientes tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
  'E. PATIOS': [
    '1.1.3	Las salidas estan señalizadas? Hay señal de aforo en los ingresos? La señaletica está en buen estado?',
    '1.1.4	Las salidas cuentan con luces de emergencia?',
    '1.1.5	Las puertas abren según flujo de evacuantes?',
    '1.1.6	En caso de contener mas de 100 de aforo, las puertas poseen barra antipanico?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.4.1	Hays estaciones manuales cerca a los ingresos?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '2.5.1	Las estructuras de madera presentan apolillamiento o pandeos?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.7	Las carcazas de motoreres electricos, aires acondiconados, bebederos, estan conectados al circuito a tierra?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.1.12	Los tomacorrientes son hermeticos tipo hidrobo o similar?',
    '3.2.1	las rampas tienen pendiente menor de 12%, estan señalizadas con franjas amarillas antideslizantes y tienen barandas a ambos lados?',
    '3.2.3	Las mallas raschel de las coberturas se encuentran en estado optimo, con ojales y armellas sin oxido?',
    '3.3.1	Las estructuras de paneles publicitarios son seguras, tienen anclajes, no presentan óxido o corrosión, inclinaciones?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.3	Las estructuras de soporte de equipos de aire acondicionado, condensadores y otros, están adecuadamente fijadas, no presentan óxido ni corrosión?',
    '3.3.5	Los juegos infantiles de carpintería metálica, de madera o plástico, son estables, seguros, están bien instalados y en buen estado?',
    'S/N	Otras observaciones',
  ],
  'F. ESCALERAS': [
    '1.1.4	Tiene luces de emergencia en su recorrido?',
    '1.1.7	No cuenta con material combustible o inflamable debajo de las escaleras que sirvan como medios de evacuación (cartones, muebles, plásticos otros similares)?',
    '1.1.8	Minimo de ancho de escalera: - 1.20m.(general)- 0.90m.(oficinas, industria o servicios)',
    '1.1.8	Minimo de ancho de paso: -0.25m.(industria), -0.28m.(comercio, oficinas, hospedaje, servcios comunales)., -0.30m. (educación, salud, recreacion, deportes, transporte).',
    '1.1.8	Minimo de alto de contrapaso: 0.18m. (general).',
    '1.1.8	Minimo ancho de descanso:- 0.90m. (escalera lineal).- el mismo ancho de la escalera (escalera que dobla)',
    '1.1.8	Tiene pasamanos a ambos lados incluyendo los descansos?',
    '1.1.8	Todos los pasos tienen franjas amarillas?',
    '1.1.8	Todos los filos son antideslizantes?',
    '1.1.9	Las escaleras son continuas desde el primer piso hasta el ultimo piso. (a excepcion del sotano)',
    '1.1.9	Si la escalera sigue al sotano tiene barreras de contencion?',
    '1.3.13	Las escaleras protegidas tienen cerramiento cortafuego?',
    '2.6.1	Las estructuras metalicas presentan deformaciones y los pernos y soldaduras son seguros?',
    '2.6.2	Las estructuras metalicas presentan oxido y corrosión?',
    '3.1.8	Las estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.2.2	Las escaleras que dan hacia el vacio tienen barandas a 1.00 minimo de altura?',
    '3.2.2	Las barandas al vacio tienen separacion maxima de 15cm (no debe pasar una esfera de 15cm.',
    'S/N	Otras observaciones',
  ],
  'G. CTO. TECNICO': [
    '1.1.3	Posee en el ingreso la señaletica fotoluminiscente de RIESGO ELECTRICO, NO INGRESAR Y USO EPP?',
    '1.1.4	Tiene luces de emergencia operativa e ininterrumpida?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.2	Posee extintor cerca para fuego tipo C?',
    '1.4.1	Tiene detector de humo operativo?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.7	Las carcazas de los equipos electricos, como  racks de servidores, UPS, transformadores, estabilizadores, aires acondiconados, bombas, estan conectados al circuito a tierra? (no considerar a los tableros electricos)',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.3.3	Las estructuras de soporte de equipos de aire acondicionado, racks de servidores o tableros, están adecuadamente fijadas, y no presentan óxido ni corrosión?',
    'S/N	Otras observaciones: Sobre los equipos hay equipos de A.A. o tuberias de agua o desague?',
  ],
  'H. ADMINISTRACION': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.2	Posee extintor cerca para fuego tipo A, B y C?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los equipos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.7	Las carcazas de los equipos electricos, como  racks de servidores, estabilizadores, aires acondiconados, estan conectados al circuito a tierra?',
    '3.1.8	Las mesas o estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.3	Las estructuras de soporte de equipos de racks de servidores y aire acondicionado, están adecuadamente fijadas, y no presentan óxido ni corrosión?',
    '3.3.6	Las mamparas tienen elementos visuales para evitar choques? Hay espejos o vidrios con la lamina de seguridad o son templados?',
    'S/N	Otras observaciones',
  ],
  'I. COCINA': [
    '1.1.1	Los pasillos internos cumplen las medidas mínimas (90cm)',
    '1.1.3	La Valvula de gas posee señaletica?',
    '1.1.4	Tiene luces de emergencia operativa e ininterrumpida?',
    '1.2.5	Hay extensiones o adaptadores?',
    '1.3.5	Las mangueras del tipo flexible de los balones se encuentran en buen estado, sin rajaduras, libres de grasa, limpias, con sujeción firme con abrazaderas',
    '1.3.6	Las tuberias de GLP, son de cobre o fierro galvanizado y estan pintadas? La valvula de gas es accesible?',
    '1.4.1	Tiene detector de humo operativo? O sensor si es que hay plancha de cocina.',
    '1.4.2	Posee extintor cerca y correctamente ubicado para fuego tipo K?',
    '2.3.1	En los techos, muros, columnas o pisos hay rajaduras o deformaciones?',
    '2.3.1	En los techos, muros, columnas o pisos hay humedad o salitre?',
    '3.1.6	Los artefactos electricos tienen conexión enchufe con espiga a tierra?',
    '3.1.7	Las campana, esta conectada al circuito a tierra?',
    '3.1.8	Las mesas o estructuras metalicas con equipamiento electrico al alcance de una persona estan aterradas?',
    '3.1.11	Hay cables expuestos o canaletas sueltas?',
    '3.1.12	Las cajas de paso tienen tapa?',
    '3.1.12	Los tomacorrientes cerca al agua son hidrobox?',
    '3.2.3	Hay objetos sueltos en los techos, como luminarias, ventiladores, etc?',
    '3.3.4	La campana de extracción abarca toda la cocina y está en buenas condiciones?',
    '3.3.2	Los muebles, racks armarios y lockers estan bien anclados?',
    '3.3.6	Hay espejos o vidrios primarios sin la lamina de seguridad?',
    'S/N	Otras observaciones',
  ],
};

/// Lista de descripciones genéricas de respaldo.
const List<String> kDefaultDescriptions = [
  'oxidado',
  'roto',
  'faltante',
  'corrosión',
  'grieta',
  'fisura',
  'humedad',
  'desgastado',
  'suelto',
  'mal estado',
];
